### ISSUE TITLE
公钥上传错误

### ISSUE THREAD

**Issue by shindgen** [sshpem/serv00-keep-active#2]
前面已经使用命令ssh-keygen -t rsa -b 4096产生了RSA密钥对，查看时私钥公钥都有了，也已经拷贝出私钥，但在使用命令ssh-copy-id username@server_ip时出现提示：
Could not open a connection to your authentication agent.
no keys found
特意进到/home/your_user/.ssh/目录里操作也是一样

**Comment by sshpem** [comment]
“Could not open a connection to your authentication agent. ”应该是ssh登录不到服务器，可以尝试ssh username@server_ip 能否登录到服务器。
ssh-copy-id在/home/your_user下操作即可。

**Comment by shindgen** [comment]
不管用ssh username@server_ip还是ssh username@server_url都能登录到服务器，而且登录了以后马上就进入/home/your_user目录进行操作，不管使用命令ssh-copy-id username@server_ip还是命令ssh-copy-id username@server_url都是一样的提示：
Could not open a connection to your authentication agent.
no keys found

**Comment by sshpem** [comment]
尝试这个命令：ssh-copy-id -i ~/.ssh/id_rsa.pub username@server_ip

**Comment by shindgen** [comment]
> 尝试这个命令：ssh-copy-id -i ~/.ssh/id_rsa.pub username@server_ip
使用这条命令已成功上传公钥，手动触发流程也看到能登录了serv00，TG也收到信息，但看执行的过程有一个提示说消息没发出去：
![screenshot-github_com-2024_12_16-10_26_51](https://github.com/user-attachments/assets/147e6953-b1f3-465b-8942-19a4c47b0a44)

**Comment by sshpem** [comment]
正常的，这个是这一步没有执行跳过了，因为只有ssh保活失败才会执行这一步。

**Comment by shindgen** [comment]
了解了，多谢大神的代码和指导。

**Comment by sshpem** [comment]
别客气
